# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Team.create(team_id:'', team_name:'San Francisco 49ers', stadium:'Levis Stadium', wins_losses:'2-14', titles:'5', rival:'Los Angeles Rams', logo:'https://s-media-cache-ak0.pinimg.com/originals/fe/e9/28/fee9289511e5ab39c117e762d8927858.jpg', abbr:'SF')
Team.create(team_id:'', team_name:'Green Bay Packers', stadium:'Lambeau Field', wins_losses:'10-6', titles:'4', rival:'Chicago Bears', logo:'https://s-media-cache-ak0.pinimg.com/originals/a0/05/be/a005be44eaeb48187059089b9edb5634.jpg', abbr:'GB')
Team.create(team_id:'', team_name:'Atlanta Falcons', stadium:'Mercedes-Benz Stadium', wins_losses:'11-5', titles:'0', rival:'New Orleans Saints', logo:'https://s-media-cache-ak0.pinimg.com/originals/c3/27/0b/c3270ba18cbbbc8957dce9ae379bfdc2.jpg', abbr:'ATL')
Team.create(team_id:'', team_name:'Seattle Seahawks', stadium:'CenturyLink Field', wins_losses:'10-5-1', titles:'1', rival:'Arizona Cardinals', logo:'http://cdn.pcwallart.com/images/seattle-seahawks-logo-wallpaper-3.jpg', abbr:'SEA')
Team.create(team_id:'', team_name:'Los Angeles Rams', stadium:'Los Angeles Memorial Coliseum', wins_losses:'4-12', titles:'1', rival:'San Francisco 49ers', logo:'https://s-media-cache-ak0.pinimg.com/originals/b9/4e/af/b94eaf0efef6dd3f142f7964a80e66a8.jpg', abbr:'LA')
Team.create(team_id:'', team_name:'Baltimore Ravens', stadium:'M&T Bank Stadium', wins_losses:'8-8', titles:'2', rival:'Pittsburgh Steelers', logo:'http://theaosn.com/wp-content/uploads/2014/04/Baltimore-Ravens-Logo-Purple-Background.jpg', abbr:'BAL')
Team.create(team_id:'', team_name:'Houston Texans', stadium:'NRG Stadium', wins_losses:'9-7', titles:'0', rival:'Indianapolis Colts', logo:'http://logodatabases.com/wp-content/uploads/2012/05/houston-texans-logo-red.jpg', abbr:'HOU')
Team.create(team_id:'', team_name:'Buffalo Bills', stadium:'New Era Field', wins_losses:'7-9', titles:'0', rival:'Miami Dolphins', logo:'http://logodatabases.com/wp-content/uploads/2012/05/buffalo-bills-logo-red-1024x768.jpg', abbr:'BUF')
Team.create(team_id:'', team_name:'Chicago Bears', stadium:'Soldier Field', wins_losses:'3-13', titles:'1', rival:'Green Bay Packers', logo:'http://logodatabases.com/wp-content/uploads/2012/05/chicago-bears-logo-c.jpg', abbr:'CHI')
Team.create(team_id:'', team_name:'Indianapolis Colts', stadium:'Lucas Oil Stadium', wins_losses:'8-8', titles:'2', rival:'Tennessee Titans', logo:'http://wallpapercave.com/wp/bJHXNeD.jpg', abbr:'IND')
Team.create(team_id:'', team_name:'Jacksonville Jaguars', stadium:'EverBank Field', wins_losses:'3-13', titles:'0', rival:'Tennessee Titans', logo:'https://s-media-cache-ak0.pinimg.com/originals/ce/26/86/ce26866638c69534e2c907188d77ea61.jpg', abbr:'JAC')
Team.create(team_id:'', team_name:'Cincinnati Bengals', stadium:'Paul Brown Stadium', wins_losses:'6-9-1', titles:'0', rival:'Pittsburgh Steelers', logo:'http://logodatabases.com/wp-content/uploads/2012/05/cincinnati-bengals-logo-wallpaper.jpg', abbr:'CIN')
Team.create(team_id:'', team_name:'Cleveland Browns', stadium:'FirstEnergy Stadium', wins_losses:'1-15', titles:'0', rival:'Pittsburgh Steelers', logo:'https://s-media-cache-ak0.pinimg.com/originals/ca/7b/b1/ca7bb1780566c5ab817e3a6b6d965749.jpg', abbr:'CLE')
Team.create(team_id:'', team_name:'Dallas Cowboys', stadium:'AT&T Stadium', wins_losses:'13-3', titles:'5', rival:'Washington Redskins', logo:'https://www.pixelstalk.net/wp-content/uploads/2015/12/Dallas-Cowboys-Logo-13.jpg', abbr:'DAL')
Team.create(team_id:'', team_name:'Detroit Lions', stadium:'Ford Field', wins_losses:'9-7', titles:'0', rival:'Green Bay Packers', logo:'https://s-media-cache-ak0.pinimg.com/originals/c8/48/c5/c848c58c527c2724a2c8e61cb0ef22d7.jpg', abbr:'DET')
Team.create(team_id:'', team_name:'Kansas City Chiefs', stadium:'Arrowhead Stadium', wins_losses:'12-4', titles:'1', rival:'Oakland Raiders', logo:'https://s-media-cache-ak0.pinimg.com/originals/ea/b3/00/eab3005ed8de24d7f699850ac0701c3b.jpg', abbr:'KC')
Team.create(team_id:'', team_name:'Los Angeles Chargers', stadium:'StubHub Center', wins_losses:'5-11', titles:'0', rival:'Denver Broncos', logo:'http://logodatabases.com/wp-content/uploads/2012/05/san-diego-chargers-logo-wallpaper.jpg', abbr:'SD')
Team.create(team_id:'', team_name:'Miami Dolphins', stadium:'Hard Rock Stadium', wins_losses:'10-6', titles:'2', rival:'Buffalo Bills', logo:'https://s-media-cache-ak0.pinimg.com/originals/e0/b3/b2/e0b3b25f34bb30077b19c1fa5e8a1251.jpg', abbr:'MIA')
Team.create(team_id:'', team_name:'New Orleans Saints', stadium:'Mercedes-Benz Superdome', wins_losses:'7-9', titles:'1', rival:'Atlanta Falcons', logo:'https://s-media-cache-ak0.pinimg.com/originals/b4/d5/5e/b4d55e1637fbe4816a518e5ce6e41526.jpg', abbr:'NO')
Team.create(team_id:'', team_name:'New York Giants', stadium:'MetLife Stadium', wins_losses:'11-5', titles:'4', rival:'Dallas Cowboys', logo:'https://idigitalcitizen.files.wordpress.com/2010/04/new-york-giants-ny-white-ipad-1024x1024.jpg', abbr:'NYG')
Team.create(team_id:'', team_name:'Carolina Panthers', stadium:'Bank Of America Stadium', wins_losses:'6-10', titles:'0', rival:'Atlanta Falcons', logo:'https://i.ytimg.com/vi/fO34pygx8ao/maxresdefault.jpg', abbr:'CAR')
Team.create(team_id:'', team_name:'Tampa Bay Buccaneers', stadium:'Raymond James Stadium', wins_losses:'9-7', titles:'1', rival:'Carolina Panthers', logo:'http://prod.static.buccaneers.clubs.nfl.com/assets/images/wallpapers/LogoLockup-1024.jpg', abbr:'TB')
Team.create(team_id:'', team_name:'New York Jets', stadium:'MetLife Stadium', wins_losses:'5-11', titles:'1', rival:'New England Patriots', logo:'https://s-media-cache-ak0.pinimg.com/originals/a2/10/ca/a210ca73562a61437d6687ecae6fd701.jpg', abbr:'NYJ')
Team.create(team_id:'', team_name:'Oakland Raiders', stadium:'Oakland–Alameda County Coliseum', wins_losses:'12-4', titles:'3', rival:'Kansas City Chiefs', logo:'https://s-media-cache-ak0.pinimg.com/originals/10/a9/8a/10a98ad12fa5e46e2ec8261c4eafb079.jpg', abbr:'OAK')
Team.create(team_id:'', team_name:'Philadelphia Eagles', stadium:'Lincoln Financial Field', wins_losses:'7-9', titles:'0', rival:'New York Giants', logo:'http://1000logos.net/wp-content/uploads/2017/05/emblem-Philadelphia-Eagles.jpg', abbr:'PHI')
Team.create(team_id:'', team_name:'Pittsburgh Steelers', stadium:'Heinz Field', wins_losses:'11-5', titles:'6', rival:'Baltimore Ravens', logo:'https://s-media-cache-ak0.pinimg.com/originals/7d/21/57/7d2157acd20dd730c77f9b31bc03415d.jpg', abbr:'PIT')
Team.create(team_id:'', team_name:'Washington Redskins', stadium:'FedEx Field', wins_losses:'8-7-1', titles:'3', rival:'Dallas Cowboys', logo:'https://s-media-cache-ak0.pinimg.com/originals/08/a8/77/08a8774217afa2e6bb14c0d2d96d9557.jpg', abbr:'WAS')
Team.create(team_id:'', team_name:'New England Patriots', stadium:'Gillette Stadium', wins_losses:'14-2', titles:'5', rival:'New York Jets', logo:'https://s-media-cache-ak0.pinimg.com/originals/fa/d6/74/fad674c6f1a449aa760267f6f667fedc.jpg', abbr:'NE')
Team.create(team_id:'', team_name:'Minnesota Vikings', stadium:'U.S. Bank Stadium', wins_losses:'8-8', titles:'0', rival:'Green Bay Packers', logo:'https://i.ytimg.com/vi/vW63O5ZwB4Y/maxresdefault.jpg', abbr:'MIN')
Team.create(team_id:'', team_name:'Denver Broncos', stadium:'Sports Authority Field at Mile High', wins_losses:'9-7', titles:'3', rival:'Oakland Raiders', logo:'https://www.deluxe.com/blog/wp-content/uploads/2014/01/Denver_Broncos_Logo.jpg', abbr:'DEN')
Team.create(team_id:'', team_name:'Tennessee Titans', stadium:'Nissan Stadium', wins_losses:'9-7', titles:'0', rival:'Houston Texans', logo:'http://cdn.wallpapersafari.com/29/52/8a3rZu.jpg', abbr:'TEN')
Team.create(team_id:'', team_name:'Arizona Cardinals', stadium:'University of Phoenix Stadium', wins_losses:'7-8-1', titles:'0', rival:'Seattle Seahawks', logo:'https://s-media-cache-ak0.pinimg.com/originals/8f/be/8a/8fbe8a9106d0f64c68949c0e26b774bd.jpg', abbr:'ARI')



#NFL games

Scoreboard.create(week:1, away_team:'Green Bay Packers', home_team:'Jacksonville Jaguars', away_points:27, home_points:23)
Scoreboard.create(week:1, away_team:'Minnesota Vikings', home_team:'Tennessee Titans', away_points:25, home_points:16)
Scoreboard.create(week:1, away_team:'Chicago Bears', home_team:'Houston Texans', away_points:14, home_points:23)
Scoreboard.create(week:1, away_team:'New York Giants', home_team:'Dallas Cowboys', away_points:20, home_points:19)
Scoreboard.create(week:1, away_team:'Tampa Bay Buccaneers', home_team:'Atlanta Falcons', away_points:31, home_points:24)
Scoreboard.create(week:1, away_team:'Buffalo Bills', home_team:'Baltimore Ravens', away_points:7, home_points:13)
Scoreboard.create(week:1, away_team:'Carolina Panthers', home_team:'Denver Broncos', away_points:20, home_points:21)
Scoreboard.create(week:1, away_team:'New England Patriots', home_team:'Arizona Cardinals', away_points:23, home_points:21)
Scoreboard.create(week:1, away_team:'Detroit Lions', home_team:'Indianapolis Colts', away_points:39, home_points:35)
Scoreboard.create(week:1, away_team:'Cincinnati Bengals', home_team:'New York Jets', away_points:23, home_points:22)
Scoreboard.create(week:1, away_team:'Pittsburgh Steelers', home_team:'Washington Redskins', away_points:38, home_points:16)
Scoreboard.create(week:1, away_team:'Oakland Raiders', home_team:'New Orleans Saints', away_points:35, home_points:34)
Scoreboard.create(week:1, away_team:'Los Angeles Rams', home_team:'San Francisco 49ers', away_points:0, home_points:28)
Scoreboard.create(week:1, away_team:'Cleveland Browns', home_team:'Philadelphia Eagles', away_points:10, home_points:29)
Scoreboard.create(week:1, away_team:'San Diego Chargers', home_team:'Kansas City Chiefs', away_points:27, home_points:33)
Scoreboard.create(week:1, away_team:'Miami Dolphins', home_team:'Seattle Seahawks', away_points:10, home_points:12)
Scoreboard.create(week:2, away_team:'Philadelphia Eagles', home_team:'Chicago Bears', away_points:29, home_points:14)
Scoreboard.create(week:2, away_team:'Baltimore Ravens', home_team:'Cleveland Browns', away_points:25, home_points:20)
Scoreboard.create(week:2, away_team:'Atlanta Falcons', home_team:'Oakland Raiders', away_points:35, home_points:28)
Scoreboard.create(week:2, away_team:'Tampa Bay Buccaneers', home_team:'Arizona Cardinals', away_points:7, home_points:40)
Scoreboard.create(week:2, away_team:'Cincinnati Bengals', home_team:'Pittsburgh Steelers', away_points:16, home_points:24)
Scoreboard.create(week:2, away_team:'Dallas Cowboys', home_team:'Washington Redskins', away_points:27, home_points:23)
Scoreboard.create(week:2, away_team:'Kansas City Chiefs', home_team:'Houston Texans', away_points:12, home_points:19)
Scoreboard.create(week:2, away_team:'San Francisco 49ers', home_team:'Carolina Panthers', away_points:27, home_points:46)
Scoreboard.create(week:2, away_team:'New York Jets', home_team:'Buffalo Bills', away_points:37, home_points:31)
Scoreboard.create(week:2, away_team:'New Orleans Saints', home_team:'New York Giants', away_points:13, home_points:16)
Scoreboard.create(week:2, away_team:'Indianapolis Colts', home_team:'Denver Broncos', away_points:20, home_points:34)
Scoreboard.create(week:2, away_team:'Tennessee Titans', home_team:'Detroit Lions', away_points:16, home_points:15)
Scoreboard.create(week:2, away_team:'Seattle Seahawks', home_team:'Los Angeles Rams', away_points:3, home_points:9)
Scoreboard.create(week:2, away_team:'Miami Dolphins', home_team:'New England Patriots', away_points:24, home_points:31)
Scoreboard.create(week:2, away_team:'Green Bay Packers', home_team:'Minnesota Vikings', away_points:14, home_points:17)
Scoreboard.create(week:2, away_team:'Jacksonville Jaguars', home_team:'San Diego Chargers', away_points:14, home_points:38)
Scoreboard.create(week:3, away_team:'Arizona Cardinals', home_team:'Buffalo Bills', away_points:18, home_points:33)
Scoreboard.create(week:3, away_team:'San Diego Chargers', home_team:'Indianapolis Colts', away_points:22, home_points:26)
Scoreboard.create(week:3, away_team:'Cleveland Browns', home_team:'Miami Dolphins', away_points:24, home_points:30)
Scoreboard.create(week:3, away_team:'Washington Redskins', home_team:'New York Giants', away_points:29, home_points:27)
Scoreboard.create(week:3, away_team:'Detroit Lions', home_team:'Green Bay Packers', away_points:27, home_points:34)
Scoreboard.create(week:3, away_team:'San Francisco 49ers', home_team:'Seattle Seahawks', away_points:18, home_points:37)
Scoreboard.create(week:3, away_team:'Baltimore Ravens', home_team:'Jacksonville Jaguars', away_points:19, home_points:17)
Scoreboard.create(week:3, away_team:'Oakland Raiders', home_team:'Tennessee Titans', away_points:17, home_points:10)
Scoreboard.create(week:3, away_team:'Houston Texans', home_team:'New England Patriots', away_points:0, home_points:27)
Scoreboard.create(week:3, away_team:'Denver Broncos', home_team:'Cincinnati Bengals', away_points:29, home_points:17)
Scoreboard.create(week:3, away_team:'Los Angeles Rams', home_team:'Tampa Bay Buccaneers', away_points:37, home_points:32)
Scoreboard.create(week:3, away_team:'New York Jets', home_team:'Kansas City Chiefs', away_points:3, home_points:24)
Scoreboard.create(week:3, away_team:'Pittsburgh Steelers', home_team:'Philadelphia Eagles', away_points:3, home_points:34)
Scoreboard.create(week:3, away_team:'Chicago Bears', home_team:'Dallas Cowboys', away_points:17, home_points:31)
Scoreboard.create(week:3, away_team:'Atlanta Falcons', home_team:'New Orleans Saints', away_points:45, home_points:32)
Scoreboard.create(week:3, away_team:'Minnesota Vikings', home_team:'Carolina Panthers', away_points:22, home_points:10)
Scoreboard.create(week:4, away_team:'Buffalo Bills', home_team:'New England Patriots', away_points:16, home_points:0)
Scoreboard.create(week:4, away_team:'New York Giants', home_team:'Minnesota Vikings', away_points:10, home_points:24)
Scoreboard.create(week:4, away_team:'Miami Dolphins', home_team:'Cincinnati Bengals', away_points:7, home_points:22)
Scoreboard.create(week:4, away_team:'Carolina Panthers', home_team:'Atlanta Falcons', away_points:33, home_points:48)
Scoreboard.create(week:4, away_team:'Oakland Raiders', home_team:'Baltimore Ravens', away_points:28, home_points:27)
Scoreboard.create(week:4, away_team:'Dallas Cowboys', home_team:'San Francisco 49ers', away_points:24, home_points:17)
Scoreboard.create(week:4, away_team:'Detroit Lions', home_team:'Chicago Bears', away_points:14, home_points:17)
Scoreboard.create(week:4, away_team:'New Orleans Saints', home_team:'San Diego Chargers', away_points:35, home_points:34)
Scoreboard.create(week:4, away_team:'Denver Broncos', home_team:'Tampa Bay Buccaneers', away_points:27, home_points:7)
Scoreboard.create(week:4, away_team:'Indianapolis Colts', home_team:'Jacksonville Jaguars', away_points:27, home_points:30)
Scoreboard.create(week:4, away_team:'Cleveland Browns', home_team:'Washington Redskins', away_points:20, home_points:31)
Scoreboard.create(week:4, away_team:'Seattle Seahawks', home_team:'New York Jets', away_points:27, home_points:17)
Scoreboard.create(week:4, away_team:'Kansas City Chiefs', home_team:'Pittsburgh Steelers', away_points:14, home_points:43)
Scoreboard.create(week:4, away_team:'Tennessee Titans', home_team:'Houston Texans', away_points:20, home_points:27)
Scoreboard.create(week:4, away_team:'Los Angeles Rams', home_team:'Arizona Cardinals', away_points:17, home_points:13)
Scoreboard.create(week:5, away_team:'New York Jets', home_team:'Pittsburgh Steelers', away_points:13, home_points:31)
Scoreboard.create(week:5, away_team:'Houston Texans', home_team:'Minnesota Vikings', away_points:13, home_points:31)
Scoreboard.create(week:5, away_team:'New York Giants', home_team:'Green Bay Packers', away_points:16, home_points:23)
Scoreboard.create(week:5, away_team:'Atlanta Falcons', home_team:'Denver Broncos', away_points:23, home_points:16)
Scoreboard.create(week:5, away_team:'Buffalo Bills', home_team:'Los Angeles Rams', away_points:30, home_points:19)
Scoreboard.create(week:5, away_team:'Washington Redskins', home_team:'Baltimore Ravens', away_points:16, home_points:10)
Scoreboard.create(week:5, away_team:'Philadelphia Eagles', home_team:'Detroit Lions', away_points:23, home_points:24)
Scoreboard.create(week:5, away_team:'Tampa Bay Buccaneers', home_team:'Carolina Panthers', away_points:17, home_points:14)
Scoreboard.create(week:5, away_team:'Chicago Bears', home_team:'Indianapolis Colts', away_points:23, home_points:29)
Scoreboard.create(week:5, away_team:'San Diego Chargers', home_team:'Oakland Raiders', away_points:31, home_points:34)
Scoreboard.create(week:5, away_team:'Cincinnati Bengals', home_team:'Dallas Cowboys', away_points:14, home_points:28)
Scoreboard.create(week:5, away_team:'Arizona Cardinals', home_team:'San Francisco 49ers', away_points:33, home_points:21)
Scoreboard.create(week:5, away_team:'New England Patriots', home_team:'Cleveland Browns', away_points:33, home_points:13)
Scoreboard.create(week:5, away_team:'Tennessee Titans', home_team:'Miami Dolphins', away_points:30, home_points:17)
Scoreboard.create(week:6, away_team:'Atlanta Falcons', home_team:'Seattle Seahawks', away_points:24, home_points:26)
Scoreboard.create(week:6, away_team:'Baltimore Ravens', home_team:'New York Giants', away_points:23, home_points:27)
Scoreboard.create(week:6, away_team:'Los Angeles Rams', home_team:'Detroit Lions', away_points:28, home_points:31)
Scoreboard.create(week:6, away_team:'Jacksonville Jaguars', home_team:'Chicago Bears', away_points:17, home_points:16)
Scoreboard.create(week:6, away_team:'Pittsburgh Steelers', home_team:'Miami Dolphins', away_points:15, home_points:30)
Scoreboard.create(week:6, away_team:'Kansas City Chiefs', home_team:'Oakland Raiders', away_points:26, home_points:10)
Scoreboard.create(week:6, away_team:'Carolina Panthers', home_team:'New Orleans Saints', away_points:38, home_points:41)
Scoreboard.create(week:6, away_team:'Philadelphia Eagles', home_team:'Washington Redskins', away_points:20, home_points:27)
Scoreboard.create(week:6, away_team:'San Francisco 49ers', home_team:'Buffalo Bills', away_points:16, home_points:45)
Scoreboard.create(week:6, away_team:'Indianapolis Colts', home_team:'Houston Texans', away_points:23, home_points:26)
Scoreboard.create(week:6, away_team:'Dallas Cowboys', home_team:'Green Bay Packers', away_points:30, home_points:16)
Scoreboard.create(week:6, away_team:'Cleveland Browns', home_team:'Tennessee Titans', away_points:26, home_points:28)
Scoreboard.create(week:6, away_team:'New York Jets', home_team:'Arizona Cardinals', away_points:3, home_points:28)
Scoreboard.create(week:6, away_team:'Cincinnati Bengals', home_team:'New England Patriots', away_points:17, home_points:35)
Scoreboard.create(week:6, away_team:'Denver Broncos', home_team:'San Diego Chargers', away_points:13, home_points:21)
Scoreboard.create(week:7, away_team:'Seattle Seahawks', home_team:'Arizona Cardinals', away_points:6, home_points:6)
Scoreboard.create(week:7, away_team:'Houston Texans', home_team:'Denver Broncos', away_points:9, home_points:27)
Scoreboard.create(week:7, away_team:'Baltimore Ravens', home_team:'New York Jets', away_points:16, home_points:24)
Scoreboard.create(week:7, away_team:'Indianapolis Colts', home_team:'Tennessee Titans', away_points:34, home_points:26)
Scoreboard.create(week:7, away_team:'San Diego Chargers', home_team:'Atlanta Falcons', away_points:33, home_points:30)
Scoreboard.create(week:7, away_team:'Washington Redskins', home_team:'Detroit Lions', away_points:17, home_points:20)
Scoreboard.create(week:7, away_team:'Cleveland Browns', home_team:'Cincinnati Bengals', away_points:17, home_points:31)
Scoreboard.create(week:7, away_team:'Chicago Bears', home_team:'Green Bay Packers', away_points:10, home_points:26)
Scoreboard.create(week:7, away_team:'New Orleans Saints', home_team:'Kansas City Chiefs', away_points:21, home_points:27)
Scoreboard.create(week:7, away_team:'New York Giants', home_team:'Los Angeles Rams', away_points:17, home_points:10)
Scoreboard.create(week:7, away_team:'Buffalo Bills', home_team:'Miami Dolphins', away_points:25, home_points:28)
Scoreboard.create(week:7, away_team:'Minnesota Vikings', home_team:'Philadelphia Eagles', away_points:10, home_points:21)
Scoreboard.create(week:7, away_team:'New England Patriots', home_team:'Pittsburgh Steelers', away_points:27, home_points:16)
Scoreboard.create(week:7, away_team:'Tampa Bay Buccaneers', home_team:'San Francisco 49ers', away_points:34, home_points:17)
Scoreboard.create(week:7, away_team:'Oakland Raiders', home_team:'Jacksonville Jaguars', away_points:33, home_points:16)
Scoreboard.create(week:8, away_team:'Kansas City Chiefs', home_team:'Indianapolis Colts', away_points:30, home_points:14)
Scoreboard.create(week:8, away_team:'San Diego Chargers', home_team:'Denver Broncos', away_points:19, home_points:27)
Scoreboard.create(week:8, away_team:'Detroit Lions', home_team:'Houston Texans', away_points:13, home_points:20)
Scoreboard.create(week:8, away_team:'Seattle Seahawks', home_team:'New Orleans Saints', away_points:20, home_points:25)
Scoreboard.create(week:8, away_team:'Minnesota Vikings', home_team:'Chicago Bears', away_points:10, home_points:20)
Scoreboard.create(week:8, away_team:'Arizona Cardinals', home_team:'Carolina Panthers', away_points:20, home_points:30)
Scoreboard.create(week:8, away_team:'Philadelphia Eagles', home_team:'Dallas Cowboys', away_points:23, home_points:29)
Scoreboard.create(week:8, away_team:'New York Jets', home_team:'Cleveland Browns', away_points:31, home_points:28)
Scoreboard.create(week:8, away_team:'Green Bay Packers', home_team:'Atlanta Falcons', away_points:32, home_points:33)
Scoreboard.create(week:8, away_team:'Washington Redskins', home_team:'Cincinnati Bengals', away_points:27, home_points:27)
Scoreboard.create(week:8, away_team:'New England Patriots', home_team:'Buffalo Bills', away_points:41, home_points:25)
Scoreboard.create(week:8, away_team:'Oakland Raiders', home_team:'Tampa Bay Buccaneers', away_points:30, home_points:24)
Scoreboard.create(week:8, away_team:'Jacksonville Jaguars', home_team:'Tennessee Titans', away_points:22, home_points:36)
Scoreboard.create(week:9, away_team:'Denver Broncos', home_team:'Oakland Raiders', away_points:20, home_points:30)
Scoreboard.create(week:9, away_team:'Tennessee Titans', home_team:'San Diego Chargers', away_points:35, home_points:43)
Scoreboard.create(week:9, away_team:'Atlanta Falcons', home_team:'Tampa Bay Buccaneers', away_points:43, home_points:28)
Scoreboard.create(week:9, away_team:'Pittsburgh Steelers', home_team:'Baltimore Ravens', away_points:14, home_points:21)
Scoreboard.create(week:9, away_team:'Dallas Cowboys', home_team:'Cleveland Browns', away_points:35, home_points:10)
Scoreboard.create(week:9, away_team:'New Orleans Saints', home_team:'San Francisco 49ers', away_points:41, home_points:23)
Scoreboard.create(week:9, away_team:'Carolina Panthers', home_team:'Los Angeles Rams', away_points:13, home_points:10)
Scoreboard.create(week:9, away_team:'New York Jets', home_team:'Miami Dolphins', away_points:23, home_points:27)
Scoreboard.create(week:9, away_team:'Detroit Lions', home_team:'Minnesota Vikings', away_points:22, home_points:16)
Scoreboard.create(week:9, away_team:'Buffalo Bills', home_team:'Seattle Seahawks', away_points:25, home_points:31)
Scoreboard.create(week:9, away_team:'Philadelphia Eagles', home_team:'New York Giants', away_points:23, home_points:28)
Scoreboard.create(week:9, away_team:'Jacksonville Jaguars', home_team:'Kansas City Chiefs', away_points:14, home_points:19)
Scoreboard.create(week:9, away_team:'Indianapolis Colts', home_team:'Green Bay Packers', away_points:31, home_points:26)
Scoreboard.create(week:10, away_team:'Seattle Seahawks', home_team:'New England Patriots', away_points:31, home_points:24)
Scoreboard.create(week:10, away_team:'Miami Dolphins', home_team:'San Diego Chargers', away_points:31, home_points:24)
Scoreboard.create(week:10, away_team:'Minnesota Vikings', home_team:'Washington Redskins', away_points:20, home_points:26)
Scoreboard.create(week:10, away_team:'Dallas Cowboys', home_team:'Pittsburgh Steelers', away_points:35, home_points:30)
Scoreboard.create(week:10, away_team:'Los Angeles Rams', home_team:'New York Jets', away_points:9, home_points:6)
Scoreboard.create(week:10, away_team:'San Francisco 49ers', home_team:'Arizona Cardinals', away_points:20, home_points:23)
Scoreboard.create(week:10, away_team:'Kansas City Chiefs', home_team:'Carolina Panthers', away_points:20, home_points:17)
Scoreboard.create(week:10, away_team:'Atlanta Falcons', home_team:'Philadelphia Eagles', away_points:15, home_points:24)
Scoreboard.create(week:10, away_team:'Cleveland Browns', home_team:'Baltimore Ravens', away_points:7, home_points:28)
Scoreboard.create(week:10, away_team:'Green Bay Packers', home_team:'Tennessee Titans', away_points:25, home_points:47)
Scoreboard.create(week:10, away_team:'Houston Texans', home_team:'Jacksonville Jaguars', away_points:24, home_points:21)
Scoreboard.create(week:10, away_team:'Denver Broncos', home_team:'New Orleans Saints', away_points:25, home_points:23)
Scoreboard.create(week:10, away_team:'Chicago Bears', home_team:'Tampa Bay Buccaneers', away_points:10, home_points:36)
Scoreboard.create(week:10, away_team:'Cincinnati Bengals', home_team:'New York Giants', away_points:20, home_points:21)
Scoreboard.create(week:11, away_team:'Philadelphia Eagles', home_team:'Seattle Seahawks', away_points:15, home_points:26)
Scoreboard.create(week:11, away_team:'Pittsburgh Steelers', home_team:'Cleveland Browns', away_points:24, home_points:9)
Scoreboard.create(week:11, away_team:'Green Bay Packers', home_team:'Washington Redskins', away_points:24, home_points:42)
Scoreboard.create(week:11, away_team:'Arizona Cardinals', home_team:'Minnesota Vikings', away_points:24, home_points:30)
Scoreboard.create(week:11, away_team:'Buffalo Bills', home_team:'Cincinnati Bengals', away_points:16, home_points:12)
Scoreboard.create(week:11, away_team:'New England Patriots', home_team:'San Francisco 49ers', away_points:30, home_points:17)
Scoreboard.create(week:11, away_team:'Baltimore Ravens', home_team:'Dallas Cowboys', away_points:17, home_points:27)
Scoreboard.create(week:11, away_team:'Houston Texans', home_team:'Oakland Raiders', away_points:20, home_points:27)
Scoreboard.create(week:11, away_team:'New Orleans Saints', home_team:'Carolina Panthers', away_points:20, home_points:23)
Scoreboard.create(week:11, away_team:'Jacksonville Jaguars', home_team:'Detroit Lions', away_points:19, home_points:26)
Scoreboard.create(week:11, away_team:'Miami Dolphins', home_team:'Los Angeles Rams', away_points:14, home_points:10)
Scoreboard.create(week:11, away_team:'Tampa Bay Buccaneers', home_team:'Kansas City Chiefs', away_points:19, home_points:17)
Scoreboard.create(week:11, away_team:'Tennessee Titans', home_team:'Indianapolis Colts', away_points:17, home_points:24)
Scoreboard.create(week:11, away_team:'Chicago Bears', home_team:'New York Giants', away_points:16, home_points:22)
Scoreboard.create(week:12, away_team:'New England Patriots', home_team:'New York Jets', away_points:22, home_points:17)
Scoreboard.create(week:12, away_team:'Green Bay Packers', home_team:'Philadelphia Eagles', away_points:27, home_points:13)
Scoreboard.create(week:12, away_team:'Arizona Cardinals', home_team:'Atlanta Falcons', away_points:19, home_points:38)
Scoreboard.create(week:12, away_team:'Los Angeles Rams', home_team:'New Orleans Saints', away_points:21, home_points:49)
Scoreboard.create(week:12, away_team:'Kansas City Chiefs', home_team:'Denver Broncos', away_points:30, home_points:27)
Scoreboard.create(week:12, away_team:'San Diego Chargers', home_team:'Houston Texans', away_points:21, home_points:13)
Scoreboard.create(week:12, away_team:'Washington Redskins', home_team:'Dallas Cowboys', away_points:26, home_points:31)
Scoreboard.create(week:12, away_team:'Cincinnati Bengals', home_team:'Baltimore Ravens', away_points:14, home_points:19)
Scoreboard.create(week:12, away_team:'Jacksonville Jaguars', home_team:'Buffalo Bills', away_points:21, home_points:28)
Scoreboard.create(week:12, away_team:'Seattle Seahawks', home_team:'Tampa Bay Buccaneers', away_points:5, home_points:14)
Scoreboard.create(week:12, away_team:'San Francisco 49ers', home_team:'Miami Dolphins', away_points:24, home_points:31)
Scoreboard.create(week:12, away_team:'New York Giants', home_team:'Cleveland Browns', away_points:27, home_points:13)
Scoreboard.create(week:12, away_team:'Carolina Panthers', home_team:'Oakland Raiders', away_points:32, home_points:35)
Scoreboard.create(week:12, away_team:'Tennessee Titans', home_team:'Chicago Bears', away_points:27, home_points:21)
Scoreboard.create(week:12, away_team:'Minnesota Vikings', home_team:'Detroit Lions', away_points:13, home_points:16)
Scoreboard.create(week:12, away_team:'Pittsburgh Steelers', home_team:'Indianapolis Colts', away_points:28, home_points:7)
Scoreboard.create(week:13, away_team:'Indianapolis Colts', home_team:'New York Jets', away_points:41, home_points:10)
Scoreboard.create(week:13, away_team:'Washington Redskins', home_team:'Arizona Cardinals', away_points:23, home_points:31)
Scoreboard.create(week:13, away_team:'Denver Broncos', home_team:'Jacksonville Jaguars', away_points:20, home_points:10)
Scoreboard.create(week:13, away_team:'Miami Dolphins', home_team:'Baltimore Ravens', away_points:6, home_points:38)
Scoreboard.create(week:13, away_team:'Houston Texans', home_team:'Green Bay Packers', away_points:13, home_points:21)
Scoreboard.create(week:13, away_team:'Kansas City Chiefs', home_team:'Atlanta Falcons', away_points:29, home_points:28)
Scoreboard.create(week:13, away_team:'San Francisco 49ers', home_team:'Chicago Bears', away_points:6, home_points:26)
Scoreboard.create(week:13, away_team:'Buffalo Bills', home_team:'Oakland Raiders', away_points:24, home_points:38)
Scoreboard.create(week:13, away_team:'Philadelphia Eagles', home_team:'Cincinnati Bengals', away_points:14, home_points:32)
Scoreboard.create(week:13, away_team:'Tampa Bay Buccaneers', home_team:'San Diego Chargers', away_points:28, home_points:21)
Scoreboard.create(week:13, away_team:'Los Angeles Rams', home_team:'New England Patriots', away_points:10, home_points:26)
Scoreboard.create(week:13, away_team:'New York Giants', home_team:'Pittsburgh Steelers', away_points:14, home_points:24)
Scoreboard.create(week:13, away_team:'Dallas Cowboys', home_team:'Minnesota Vikings', away_points:17, home_points:15)
Scoreboard.create(week:13, away_team:'Detroit Lions', home_team:'New Orleans Saints', away_points:28, home_points:13)
Scoreboard.create(week:13, away_team:'Carolina Panthers', home_team:'Seattle Seahawks', away_points:7, home_points:40)
Scoreboard.create(week:14, away_team:'Baltimore Ravens', home_team:'New England Patriots', away_points:23, home_points:30)
Scoreboard.create(week:14, away_team:'Washington Redskins', home_team:'Philadelphia Eagles', away_points:27, home_points:22)
Scoreboard.create(week:14, away_team:'Seattle Seahawks', home_team:'Green Bay Packers', away_points:10, home_points:38)
Scoreboard.create(week:14, away_team:'Arizona Cardinals', home_team:'Miami Dolphins', away_points:23, home_points:26)
Scoreboard.create(week:14, away_team:'New Orleans Saints', home_team:'Tampa Bay Buccaneers', away_points:11, home_points:16)
Scoreboard.create(week:14, away_team:'Denver Broncos', home_team:'Tennessee Titans', away_points:10, home_points:13)
Scoreboard.create(week:14, away_team:'Oakland Raiders', home_team:'Kansas City Chiefs', away_points:13, home_points:21)
Scoreboard.create(week:14, away_team:'Atlanta Falcons', home_team:'Los Angeles Rams', away_points:42, home_points:14)
Scoreboard.create(week:14, away_team:'Chicago Bears', home_team:'Detroit Lions', away_points:17, home_points:20)
Scoreboard.create(week:14, away_team:'New York Jets', home_team:'San Francisco 49ers', away_points:23, home_points:17)
Scoreboard.create(week:14, away_team:'Dallas Cowboys', home_team:'New York Giants', away_points:7, home_points:10)
Scoreboard.create(week:14, away_team:'Pittsburgh Steelers', home_team:'Buffalo Bills', away_points:27, home_points:20)
Scoreboard.create(week:14, away_team:'San Diego Chargers', home_team:'Carolina Panthers', away_points:16, home_points:28)
Scoreboard.create(week:14, away_team:'Minnesota Vikings', home_team:'Jacksonville Jaguars', away_points:25, home_points:16)
Scoreboard.create(week:14, away_team:'Houston Texans', home_team:'Indianapolis Colts', away_points:22, home_points:17)
Scoreboard.create(week:14, away_team:'Cincinnati Bengals', home_team:'Cleveland Browns', away_points:23, home_points:10)
Scoreboard.create(week:15, away_team:'Indianapolis Colts', home_team:'Minnesota Vikings', away_points:34, home_points:6)
Scoreboard.create(week:15, away_team:'Detroit Lions', home_team:'New York Giants', away_points:6, home_points:17)
Scoreboard.create(week:15, away_team:'Pittsburgh Steelers', home_team:'Cincinnati Bengals', away_points:24, home_points:20)
Scoreboard.create(week:15, away_team:'Los Angeles Rams', home_team:'Seattle Seahawks', away_points:3, home_points:24)
Scoreboard.create(week:15, away_team:'Tennessee Titans', home_team:'Kansas City Chiefs', away_points:19, home_points:17)
Scoreboard.create(week:15, away_team:'New Orleans Saints', home_team:'Arizona Cardinals', away_points:48, home_points:41)
Scoreboard.create(week:15, away_team:'Carolina Panthers', home_team:'Washington Redskins', away_points:26, home_points:15)
Scoreboard.create(week:15, away_team:'Philadelphia Eagles', home_team:'Baltimore Ravens', away_points:26, home_points:27)
Scoreboard.create(week:15, away_team:'Green Bay Packers', home_team:'Chicago Bears', away_points:30, home_points:27)
Scoreboard.create(week:15, away_team:'Jacksonville Jaguars', home_team:'Houston Texans', away_points:20, home_points:21)
Scoreboard.create(week:15, away_team:'New England Patriots', home_team:'Denver Broncos', away_points:16, home_points:3)
Scoreboard.create(week:15, away_team:'San Francisco 49ers', home_team:'Atlanta Falcons', away_points:13, home_points:41)
Scoreboard.create(week:15, away_team:'Oakland Raiders', home_team:'San Diego Chargers', away_points:19, home_points:16)
Scoreboard.create(week:15, away_team:'Miami Dolphins', home_team:'New York Jets', away_points:34, home_points:13)
Scoreboard.create(week:15, away_team:'Cleveland Browns', home_team:'Buffalo Bills', away_points:13, home_points:33)
Scoreboard.create(week:15, away_team:'Tampa Bay Buccaneers', home_team:'Dallas Cowboys', away_points:20, home_points:26)
Scoreboard.create(week:16, away_team:'Minnesota Vikings', home_team:'Green Bay Packers', away_points:25, home_points:38)
Scoreboard.create(week:16, away_team:'Tampa Bay Buccaneers', home_team:'New Orleans Saints', away_points:24, home_points:31)
Scoreboard.create(week:16, away_team:'Atlanta Falcons', home_team:'Carolina Panthers', away_points:33, home_points:16)
Scoreboard.create(week:16, away_team:'Washington Redskins', home_team:'Chicago Bears', away_points:41, home_points:21)
Scoreboard.create(week:16, away_team:'Tennessee Titans', home_team:'Jacksonville Jaguars', away_points:17, home_points:38)
Scoreboard.create(week:16, away_team:'New York Jets', home_team:'New England Patriots', away_points:3, home_points:41)
Scoreboard.create(week:16, away_team:'New York Giants', home_team:'Philadelphia Eagles', away_points:19, home_points:24)
Scoreboard.create(week:16, away_team:'Denver Broncos', home_team:'Kansas City Chiefs', away_points:10, home_points:33)
Scoreboard.create(week:16, away_team:'Baltimore Ravens', home_team:'Pittsburgh Steelers', away_points:27, home_points:31)
Scoreboard.create(week:16, away_team:'Arizona Cardinals', home_team:'Seattle Seahawks', away_points:34, home_points:31)
Scoreboard.create(week:16, away_team:'San Francisco 49ers', home_team:'Los Angeles Rams', away_points:22, home_points:21)
Scoreboard.create(week:16, away_team:'Cincinnati Bengals', home_team:'Houston Texans', away_points:10, home_points:12)
Scoreboard.create(week:16, away_team:'San Diego Chargers', home_team:'Cleveland Browns', away_points:17, home_points:20)
Scoreboard.create(week:16, away_team:'Indianapolis Colts', home_team:'Oakland Raiders', away_points:25, home_points:33)
Scoreboard.create(week:16, away_team:'Detroit Lions', home_team:'Dallas Cowboys', away_points:21, home_points:42)
Scoreboard.create(week:16, away_team:'Miami Dolphins', home_team:'Buffalo Bills', away_points:34, home_points:31)
Scoreboard.create(week:17, away_team:'Cleveland Browns', home_team:'Pittsburgh Steelers', away_points:24, home_points:27)
Scoreboard.create(week:17, away_team:'Chicago Bears', home_team:'Minnesota Vikings', away_points:10, home_points:38)
Scoreboard.create(week:17, away_team:'New England Patriots', home_team:'Miami Dolphins', away_points:35, home_points:14)
Scoreboard.create(week:17, away_team:'Baltimore Ravens', home_team:'Cincinnati Bengals', away_points:10, home_points:27)
Scoreboard.create(week:17, away_team:'Carolina Panthers', home_team:'Tampa Bay Buccaneers', away_points:16, home_points:17)
Scoreboard.create(week:17, away_team:'Houston Texans', home_team:'Tennessee Titans', away_points:17, home_points:24)
Scoreboard.create(week:17, away_team:'Arizona Cardinals', home_team:'Los Angeles Rams', away_points:44, home_points:6)
Scoreboard.create(week:17, away_team:'New York Giants', home_team:'Washington Redskins', away_points:19, home_points:10)
Scoreboard.create(week:17, away_team:'Dallas Cowboys', home_team:'Philadelphia Eagles', away_points:13, home_points:27)
Scoreboard.create(week:17, away_team:'New Orleans Saints', home_team:'Atlanta Falcons', away_points:32, home_points:38)
Scoreboard.create(week:17, away_team:'Buffalo Bills', home_team:'New York Jets', away_points:10, home_points:30)
Scoreboard.create(week:17, away_team:'Oakland Raiders', home_team:'Denver Broncos', away_points:6, home_points:24)
Scoreboard.create(week:17, away_team:'Jacksonville Jaguars', home_team:'Indianapolis Colts', away_points:20, home_points:24)
Scoreboard.create(week:17, away_team:'Seattle Seahawks', home_team:'San Francisco 49ers', away_points:25, home_points:23)
Scoreboard.create(week:17, away_team:'Kansas City Chiefs', home_team:'San Diego Chargers', away_points:37, home_points:27)
Scoreboard.create(week:17, away_team:'Green Bay Packers', home_team:'Detroit Lions', away_points:31, home_points:24)
